version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "52000:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp

  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - wp_data:/var/www/html
      - ../:/var/www/html/wp-content/themes/maksimer
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp

  # wordpress-cli:
  #   depends_on:
  #     - db
  #     - wordpress
  #   image: wordpress:cli
  #   user: xfs
  #   volumes:
  #     - wp_data:/var/www/html
  #     - ./compose-this.sh:/var/www/html/wp-content/themes/maksimer/compose-this.sh
  #   environment:
  #     WP_CLI_CACHE_DIR: /var/www/html/cli-cache
  #   command: "bash wp-content/themes/maksimer/compose-this.sh"

volumes:
  db_data:
  wp_data:
